#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Romain Tisserand
#
# Verilator unit test for src/pce/common/mem/sdram.sv -- the FIRST simulation of that
# module on this project. GHDL cannot compile it (SystemVerilog) and the PCE core is
# VHDL, so there is no mixed-language path; this tests sdram.sv standalone, which is
# enough for the question it answers: does port C (CD-RAM, the LOWEST-priority client --
# the chain is refresh > A > B > C) lose a write when A and B contend?
#
# Three Verilator quirks, each of which stops the build dead:
#   1. sdram.sv gives its ports default values (`input RAM_C_REQ = 1'b0`). Gowin accepts
#      that; Verilator rejects it as non-standard. A generated copy strips them -- the
#      harness connects every port explicitly, so nothing is changed by that.
#   2. `reg init_old=0;` plus a nonblocking assignment to the same reg is
#      %Error-BLKANDNBLK "Unsupported". Suppressed; it is legal Verilog and correct here.
#   3. sdram.sv instantiates the Gowin ODDR primitive for SDRAM_CLK. ODDR.v is a stub;
#      the chip model is clocked from the controller's own clk, so nothing depends on it.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../../src/pce/common/mem/sdram.sv"

python3 - "$SRC" "$HERE/sdram_vlt.sv" <<'PY'
import re, sys
s = open(sys.argv[1]).read()
i = s.find('module sdram'); j = s.find(');', i)
head, ports, tail = s[:i], s[i:j], s[j:]
ports = re.sub(r"\s*=\s*\d+'[hdb][0-9a-fA-FxzZ_]+", '', ports)
open(sys.argv[2], 'w').write(
    "// GENERATED by run_sdram_test.sh from src/pce/common/mem/sdram.sv.\n"
    "// Only change: default port values stripped. DO NOT EDIT; edit the original.\n"
    + head + ports + tail)
PY

cd "$HERE"
verilator --cc --exe --build -Wno-fatal -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC -Wno-BLKANDNBLK \
  --top-module tb_sdram_top -I. \
  tb_sdram_top.sv sdram_chip_model.sv sdram_vlt.sv ODDR.v tb_sdram.cpp -o tb_sdram
exec ./obj_dir/tb_sdram "$@"
