#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Romain Tisserand
"""Convert an Altera .mif to a VHDL package constant.

The Next engine's block RAMs come from MiSTer's bram.vhd, which wraps altsyncram and
initialises it from a .mif. Gowin has no altsyncram, so our replacement dpram takes its
initial contents from a generated package instead of a file read at synthesis time.

Usage: scripts/mif2vhd.py <in.mif> <out.vhd> <constant_name>

The generated package starts with an attribution header: the table DATA belongs to the
donor the .mif came from, so the output claims no copyright on it (see
THIRD_PARTY_LICENSES.md). Pass the .mif by its repository path so the header names it.

NECTang addition (PCE port): the ZX Next port's original version of this script parsed
addresses with plain int(addr, 0), which only ever saw decimal .mif files. PCE's
voltab.mif and huc6260_palette_init.mif both declare ADDRESS_RADIX = HEX with addresses
that actually contain hex digits (e.g. voltab.mif's "000A"), which int(addr, 0) can't
parse (a leading '0' makes Python's base-0 rule try octal and reject 'A'). Added explicit
ADDRESS_RADIX handling, mirroring the DATA_RADIX handling already here.
"""
import re, sys

def parse(path):
    txt = open(path).read()
    depth = int(re.search(r'DEPTH\s*=\s*(\d+)', txt, re.I).group(1))
    width = int(re.search(r'WIDTH\s*=\s*(\d+)', txt, re.I).group(1))
    radix_bases = {'BIN': 2, 'HEX': 16, 'DEC': 10, 'UNS': 10, 'OCT': 8}
    data_radix = re.search(r'DATA_RADIX\s*=\s*(\w+)', txt, re.I).group(1).upper()
    base = radix_bases[data_radix]
    addr_radix_m = re.search(r'ADDRESS_RADIX\s*=\s*(\w+)', txt, re.I)
    addr_base = radix_bases[addr_radix_m.group(1).upper()] if addr_radix_m else 10
    body = txt[re.search(r'CONTENT\s+BEGIN', txt, re.I).end():]
    body = body[:re.search(r'\bEND\b', body, re.I).start()]

    mem = [0] * depth
    for stmt in body.split(';'):
        stmt = stmt.strip()
        if not stmt:
            continue
        addr, vals = stmt.split(':', 1)
        addr = addr.strip()
        vals = vals.split()
        if '..' in addr:                       # [a..b] : v;  range fill
            lo, hi = (int(x, addr_base) for x in addr.strip('[]').split('..'))
            for a in range(lo, hi + 1):
                mem[a] = int(vals[0], base)
        else:                                  # a : v0 v1 v2 ...  consecutive
            a = int(addr, addr_base)
            for i, v in enumerate(vals):
                mem[a + i] = int(v, base)
    return depth, width, mem

def main():
    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
    depth, width, mem = parse(src)
    lines = [
        '-- SPDX-License-Identifier: GPL-3.0-or-later',
        "-- The table data is the TurboGrafx16_MiSTer donor's, mechanically converted from",
        '-- %s. It is NOT original work of this project and no copyright' % src,
        '-- is claimed on it here. See THIRD_PARTY_LICENSES.md for the upstream project, author and licence.',
        '',
        '-- Generated by scripts/mif2vhd.py from %s. Do not edit.' % src.split('/')[-1],
        'library ieee;',
        'use ieee.std_logic_1164.all;',
        '',
        'package %s_pkg is' % name,
        '   type %s_t is array (0 to %d) of std_logic_vector(%d downto 0);' % (name, depth - 1, width - 1),
        '   constant %s : %s_t := (' % (name, name),
    ]
    words = ['      %d => "%s"' % (i, format(v, '0%db' % width)) for i, v in enumerate(mem)]
    lines.append(',\n'.join(words))
    lines += ['   );', 'end package;', '']
    open(dst, 'w').write('\n'.join(lines))
    print('%s: %d x %d bits -> %s' % (src.split('/')[-1], depth, width, dst))

main()
